### ISSUE TITLE
Doesn't work with ASGI

### ISSUE THREAD

**Issue by califlower** [adamchainz/django-browser-reload#87] opened 2022-05-12 17:48 UTC
### Description

Hi,

I'll start by saying this project is wonderful but if for some reason you accidentally run this in production you'll end up with a completely broken asgi event loop. The browser reload code seems to hog the event loop even after a request is closed. For synchronous servers it seems to be less of an issue but with the asgi

The logs will show the following 
```
socket.send() raised exception
```

and then the worker will timeout after hanging for 10-15 seconds. It would be great to have either a warning if the browser middleware is running or maybe detect if we're using the none dev server and throw a warning that it may block the event loop

There may also be an additional problem where socket connections arent properly being closed after a page is refreshed?

**Comment by adamchainz** [comment] 2022-05-12 18:57
> if for some reason you accidentally run this in production 

Did you use `DEBUG = True` in production? That is generally unsupported by Django.

> The browser reload code seems to hog the event loop even after a request is closed. For synchronous servers it seems to be less of an issue but with the asgi

This sounds like there's a bug in gunicorn or uvicorn, or possibly Django's ASGI layer. The view is a relatively simple use of a streaming http WSGI response. This should be supported by any ASGi adapter. Would you like to try finding a minimal reproduction?

> It would be great to have either a warning if the browser middleware is running or maybe detect if we're using the none dev server and throw a warning that it may block the event loop

I'd rather fix the problems with the servers than have a workaround here.

**Comment by Alexerson** [comment] 2022-05-15 21:24
Got a similar problem today. 
Except I could reproduce with the runserver from channels with DEBUG=True locally.
I believe this can be reproduced with the project generated with cookie-cutter.

After googling around, I found this:
https://stackoverflow.com/questions/66674430/streaminghttpresponse-doesnt-block-other-requests-in-wsgi-but-does-on-channels
Or:
https://forum.djangoproject.com/t/channels-cannot-be-used-with-streaminghttpresponse/10105
So there seems to be an issue with ASGI and StreamingHttpResponse.

I’m not too sure where to report this issue though. 

Would you consider including a purely async view to handle the asgi case if this cannot be fixed directly? If so, I might try to propose something.

**Comment by Alexerson** [comment] 2022-05-15 21:26
It seems to be reported here: https://github.com/django/channels/issues/1761

**Comment by carltongibson** [comment] 2022-06-14 06:52
This will need to be fixed in Django. (Channels will drop the old `AsgiHandler` this summer, in favour of Django's, which has been available since Django v3.0.) 

Relevant tickets are: 

* [#33735 (Add Asynchronous Responses for Use With an ASGI Server) – Django](https://code.djangoproject.com/ticket/33735)
* [#32798 (StreamingHttpResponse Raises SynchronousOnlyOperation in ASGI Server) – Django](https://code.djangoproject.com/ticket/32798)

Both of these are 🎯Django 4.2.

**Comment by carltongibson** [comment] 2023-02-01 06:08
OK, yes. So sometime later, the end result was that the response will need an async iterator when running under ASGI in order to stream correctly.

**Comment by Alexerson** [comment] 2023-02-01 22:41
I can try to look at it by the end of the week if Petr is not able to.
Would the best strategy to make the events view async? If we support Django > 3.2, I think this is acceptable.
And then replace the threading.Event with asyncio.Event and something similar for the timer.

Or is that overwill and there is a simpler solution I don’t think about?

**Comment by stribny** [comment] 2023-02-01 23:06
@Alexerson I won't get to it soon, so definitely feel free to give it a go.

Either way I am also interested in what the solution should look like generally speaking. I don't have much experience with async Python yet.

**Comment by Alexerson** [comment] 2023-02-01 23:32
Sounds good. I’m pushing what I’ve done locally. I’ll continue the discussion in the PR.

**Comment by adamchainz** [comment] 2023-06-05 21:18
Fixed in #148, released in 1.9.0. Let me know how it works.

**Closed by adamchainz** 2023-06-05 21:18 UTC
